name: build

on:
  workflow_dispatch:
  
  
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      run: |
        sudo mkdir -p /workdir
        sudo mkdir -p /workdir/trilium-trans-release
        sudo chmod -R 777 /workdir
        rm translations.py && cp translations_cn.py translations.py
        git clone https://github.com/zadam/trilium.git /workdir/trilium-trans/trilium-src
        ls
        
    - name: Download
      run: |
        cd /workdir/trilium-trans/trilium-src
        curl -sL https://raw.githubusercontent.com/wrhsd1/files/main/download.sh  | sudo -E bash -  
        sudo chmod -R 777 /workdir
        
    - name: Package
      run: |
        wget https://raw.githubusercontent.com/wrhsd1/files/main/maker.sh
        wget https://raw.githubusercontent.com/wrhsd1/files/main/make_release.py
        bash maker.sh
        python3 make_release.py    
        cd /workdir/trilium-trans-release
        ls        
        
    - name: Upload to WeTransfer
      id: wetransfer
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress /workdir/trilium-trans-release/* 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
        echo "::set-output name=url::$(cat wetransfer.log | grep https | cut -f3 -d" ")"
