name: auto-build

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      run: |        
        sudo mkdir -p /workdir
        sudo mkdir -p /workdir/trilium-trans-release
        sudo chmod -R 777 /workdir
        rm translations.py && cp translations_cn.py translations.py
        git clone https://github.com/zadam/trilium.git /workdir/trilium-trans/trilium-src
        ls
        
    - name: Download
      run: |
        cd /workdir/trilium-trans/trilium-src
        curl -sL https://raw.githubusercontent.com/wrhsd1/files/main/download.sh  | sudo -E bash -  
                
   
