name: build

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      run: |           
        sudo mkdir -p /workdir
        sudo mkdir -p /workdir/trilium-trans-release
        sudo chmod -R 777 /workdir
        rm translations.py && cp translations_cn.py translations.py
        git clone https://github.com/zadam/trilium.git /workdir/trilium-trans/trilium-src
        ls
        
    - name: Download
      run: |
        cd /workdir/trilium-trans/trilium-src
        curl -sL https://raw.githubusercontent.com/wrhsd1/files/main/download.sh  | sudo -E bash -  
        sudo chmod -R 777 /workdir              
        
    - name: Get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d')"    
        
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: /workdir/trilium-trans-release/
        asset_name: |
          trilium-linux-x64-*.tar.xz
          trilium-linux-x64-server-*.tar.xz
          trilium-mac-x64-*.zip
          trilium-windows-x64-*.zip          
        asset_content_type: application/gzip
