name: build

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      run: |
        sudo mkdir -p /workdir
        sudo chmod -R 777 /workdir
        rm translations.py && cp translations_cn.py translations.py
        ls
        
    - name: Download
      run: |
        git clone https://github.com/zadam/trilium.git /workdir/trilium-trans/trilium-src
        wget https://github.com/zadam/trilium/releases/download/v0.51.2/trilium-linux-x64-0.51.2.tar.xz
        tar -xf trilium-linux-x64-0.51.2.tar.xz && mv trilium-linux-x64 /workdir/trilium-trans/
        cd /workdir/trilium-trans
        ls
        
        
